kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS_CONFIG}
  topic:
    usage-records: usage-records-topic
management:
  endpoints:
    web:
      exposure:
        include: health,info  # Ensure "health" is included
  endpoint:
    health:
      show-details: always
spring:
  security:
    filter:
      dispatcher-types: async, error, request
    ignore:
      [ "/actuator/health" ]
health:
  status:
    http-mapping:
      DOWN: 503
      OUT_OF_SERVICE: 503

logging:
  level:
    org.springframework.security: DEBUG
