kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS_CONFIG:localhost:9092}
  security:
    protocol: ${KAFKA_SECURITY_PROTOCOL}
  sasl:
    mechanism: ${KAFKA_SASL_MECHANISM}
  topic:
    usage-records: usage-records-topic
  admin:
    client-id: usage-producer-service


management:
  endpoints:
    web:
      exposure:
        include: health,info  # Ensure "health" is included
  endpoint:
    health:
      show-details: always
spring:
  security:
    filter:
      dispatcher-types: async, error, request
    ignore:
      [ "/actuator/health" ]
health:
  status:
    http-mapping:
      DOWN: 503
      OUT_OF_SERVICE: 503

aws:
  region: us-east-1  # AWS region for CloudWatch and other services
