kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS_CONFIG:localhost:9092}
  topic:
    usage-records: usage-records-topic
management:
  endpoints:
    web:
      exposure:
        include: health,info  # Ensure "health" is included
  endpoint:
    health:
      show-details: always
spring:
  security:
    filter:
      dispatcher-types: async, error, request
    ignore:
      [ "/actuator/health" ]
health:
  status:
    http-mapping:
      DOWN: 503
      OUT_OF_SERVICE: 503


logging:
  level:
    root: INFO
    com.chargebee: DEBUG  # Set log level for your package
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  file:
    name: cb-ubb-ingestion-service.log
  cloudwatch:
    enabled: false
    log-group: ecs-cb-ubb-ingestion-service-stream-logs
    log-stream: ecs-cb-ubb-ingestion-service-stream-logs
aws:
  region: us-east-1  # AWS region for CloudWatch and other services
