openapi: 3.0.3
info:
  contact:
    email: support@example.com
    name: API Support
  description: API for ingesting and managing usage data.
  title: Usage Ingestion API
  version: 1.0.0
servers:
  - description: Production Server
    url: 'https://api.example.com/v1'
  - description: Staging Server
    url: 'https://staging-api.example.com/v1'
  - description: Local Server
    url: 'http://localhost:3000'
security:
  - X-API-Key: []
paths:
  /usage:
    post:
      description: Submit a new usage record to the system.
      operationId: ingestUsage
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsageRecord'
          application/xml:
            schema:
              properties: {}
              type: object
        description: ''
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsageRecord'
          description: Usage record created successfully.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Invalid input.
        '401':
          description: Unauthorized
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal server error.
      summary: Ingest a new usage record
      tags:
        - Usage
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
        - tag: Usage
  /status:
    get:
      summary: Get Info of the service
      tags:
        - status
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationInfo'
      operationId: get-info
      description: Get Info of the service
    parameters: []
components:
  schemas:
    UsageRecord:
      example:
        attributes:
          key: attributes
        id: id
        timestamp: '2000-01-23T04:56:07.000+00:00'
      type: object
      properties:
        id:
          description: Unique idempotency key for the usage record.
          type: string
        usage_timestamp:
          description: Indicates the usage record timestamp.
          format: date-time
          type: string
          x-stoplight:
            id: qypl1nictgm27
        attributes:
          additionalProperties:
            description: Value associated with the metadata key.
            type: string
            x-stoplight:
              id: e4b6iv0imzuj5
          type: object
        subscription_id:
          type: string
          x-stoplight:
            id: raum5egsfw7kj
        site_id:
          type: string
          x-stoplight:
            id: 5ehezwxicycij
      required:
        - usage_timestamp
        - attributes
    Error:
      properties:
        code:
          description: Error code.
          format: int32
          type: integer
        message:
          description: Error message.
          type: string
      required:
        - code
        - message
      type: object
    UsageAttribute:
      additionalProperties:
        description: Value associated with the metadata key.
        type: string
        x-stoplight:
          id: e4b6iv0imzuj5
      type: object
    ApplicationInfo:
      title: ApplicationInfo
      x-stoplight:
        id: ol42d6nh2hxr2
      properties:
        version:
          description: The version of the application.
          type: string
        buildDate:
          description: The build date of the application.
          type: string
          format: date-time
        environment:
          description: 'The environment where the application is running (e.g., production, staging).'
          type: string
        uptime:
          description: The uptime of the application.
          type: string
        memoryUsage:
          description: Current memory usage of the application.
          type: object
          properties:
            total:
              type: integer
              description: Total memory allocated.
            used:
              type: integer
              description: Memory currently in use.
            free:
              type: integer
              description: Free memory available.
        cpuUsage:
          description: Current CPU usage percentage.
          type: number
          format: float
        threadCount:
          description: Number of active threads.
          type: integer
        diskSpace:
          description: Disk usage and available space.
          type: object
          properties:
            total:
              type: integer
              description: Total disk space.
            used:
              type: integer
              description: Used disk space.
            free:
              type: integer
              description: Free disk space.
        serviceName:
          description: Name of the service.
          type: string
        commitHash:
          description: Git commit hash for the current build.
          type: string
        releaseNotes:
          description: Description of the latest changes or updates.
          type: string
      required:
        - version
        - buildDate
        - environment
        - uptime
      type: object
  securitySchemes:
    X-API-Key:
      in: header
      name: X-API-Key
      type: apiKey
