/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.0.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.chargebee.ingestion.controllers;

import com.chargebee.ingestion.models.ApplicationInfo;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-08-22T23:20:51.709090+05:30[Asia/Kolkata]")
@Validated
@Tag(name = "Status", description = "the Status API")
public interface StatusApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /status : Get Info of the service
     * Get Info of the service
     *
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "getInfo",
        summary = "Get Info of the service",
        tags = { "status" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApplicationInfo.class))
            })
        },
        security = {
            @SecurityRequirement(name = "X-API-Key")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/status",
        produces = { "application/json" }
    )
    default ResponseEntity<ApplicationInfo> getInfo(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"cpuUsage\" : 5.962134, \"environment\" : \"environment\", \"memoryUsage\" : { \"total\" : 0, \"used\" : 6, \"free\" : 1 }, \"releaseNotes\" : \"releaseNotes\", \"diskSpace\" : { \"total\" : 2, \"used\" : 7, \"free\" : 9 }, \"threadCount\" : 5, \"buildDate\" : \"2000-01-23T04:56:07.000+00:00\", \"serviceName\" : \"serviceName\", \"version\" : \"version\", \"commitHash\" : \"commitHash\", \"uptime\" : \"uptime\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
